homeassistant:
  # Name of the location where Home Assistant is running
  #name: Home
  # Location required to calculate the time the sun rises and sets
  #latitude: !secret latitude
  #longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  #elevation: 279
  # metric for Metric, imperial for Imperial
  #unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  #time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config

hacs:
  token: !secret hacs_github
  appdaemon: True

system_health:

mobile_app:

logger:
  default: error

# Enables the frontend
frontend:
  themes: !include themes.yaml

lovelace:
  mode: yaml
  resources:
    #HACS Resources (Updated Automatically)
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module
    - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/text-element/text-element.js
      type: module
    - url: /hacsfiles/lovelace-gap-card/gap-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/zha-network-card/zha-network-card.js
      type: module
    - url: /hacsfiles/Home-Assistant-Lovelace-HTML-Jinja2-Template-card/html-template-card.js
      type: module
    - url: /hacsfiles/bignumber-card/bignumber-card.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    #Non-HACS Resources
    - url: /local/custom-lovelace/weather-card/dark-sky-weather-card.js?v=7.4
      type: module
    - url: 'https://fonts.googleapis.com/css?family=Lato'
      type: css
    - url: /local/custom-lovelace/font.css?v=3
      type: css
    - url: /local/custom-lovelace/card-templater/lovelace-card-templater.js?v=0.0.2
      type: module
  dashboards:
    ui-morgan:
      mode: yaml
      filename: ui-morgan.yaml
      title: Morgan
      icon: mdi:human-female
      show_in_sidebar: true
      require_admin: false

# Enables configuration UI
config:
 

google_assistant:
  project_id: home-assistant-227322
  service_account: !include service-account.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - input_boolean
    - input_select
    - script
  entity_config:
    light.sink_1:
      expose: false
    light.sink_2:
      expose: false
    light.table_1:
      expose: false
    light.table_2:
      expose: false
    light.table_3:
      expose: false
    light.garage_1:
      expose: false
    light.garage_2:
      expose: false
    light.theater_1:
      expose: false
    light.theater_2:
      expose: false
    light.theater_3:
      expose: false
    light.entry_1:
      expose: false
    light.entry_2:
      expose: false
    light.entry_3:
      expose: false
    light.morgan_fun_1:
      expose: false
    light.morgan_fun_2:
      expose: false
    light.morgan_fun_3:
      expose: false
    light.morgan_fun_4:
      expose: false
    light.morgan_fun_5:
      expose: false
    light.basement_can_1:
      expose: false
    light.basement_can_2:
      expose: false
    light.basement_can_3:
      expose: false
    light.basement_can_4:
      expose: false
    light.basement_can_5:
      expose: false
    light.morgan_s_fun_lamp_group:
      expose: false
    light.morgankiosk:
      expose: false
    light.bottom_of_stairs_blue_led:
      expose: false
    light.bottom_of_stairs_green_led:
      expose: false
    light.bottom_of_stairs_red_led:
      expose: false
    light.entry_blue_led:
      expose: false
    light.entry_green_led:
      expose: false
    light.entry_red_led:
      expose: false
    light.top_of_stairs_blue_led:
      expose: false
    light.top_of_stairs_green_led:
      expose: false
    light.top_of_stairs_red_led:
      expose: false
    light.blue_room_switch_red_led:
      expose: false
    light.blue_room_switch_white_led:
      expose: false
    light.back_door_switch_red_led:
      expose: false
    light.back_door_switch_white_led:
      expose: false
    light.theater_switch_red_led:
      expose: false
    light.theater_switch_white_led:
      expose: false
    light.bar_blue_led:
      expose: false
    light.bar_green_led:
      expose: false
    light.bar_red_led:
      expose: false
    light.julie_phone:
      expose: false
    input_boolean.show_commute:
      expose: false
    input_boolean.alex_bed:
      expose: false
    input_boolean.alex_basement:
      expose: false
    input_boolean.julie_bed:
      expose: false
    input_boolean.alarm_clock:
      expose: false
    input_boolean.check_config:
      expose: false
    input_boolean.valid_config:
      expose: false
    script.cc_skip:
      expose: false
    script.check_config:
      expose: false
    script.gledopto_on_off:
      expose: false
    script.media_mute:
      expose: false
    script.xbox_play_pause:
      expose: false
    script.xbox_stop:
      expose: false
    switch.garage_opener_restart:
      expose: false
    switch.garage_buzzer:
      expose: false
    switch.outdoor_plug_2:
      name: Humidifier
    switch.adguard_filtering:
      expose: false
    switch.adguard_parental_control:
      expose: false
    switch.adguard_protection:
      expose: false
    switch.adguard_safe_browsing:
      expose: false
    switch.adguard_safe_search:
      expose: false
    light.kitchen_sink:
      name: KITCHEN SINK
      aliases:
        - ISLAND LIGHTS

# Discover some devices automatically
discovery:

#zeroconf:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Recorder customization
recorder:
  db_url: !secret db_url
  purge_keep_days: 5
  include:
    domains:
      - light
      - switch
      - device_tracker
      - input_boolean
    entities:
      - cover.garage_door
      - binary_sensor.front_door
      - binary_sensor.garage_entry_door
      - binary_sensor.upstairs_back_door
      - binary_sensor.downstairs_back_door
  exclude:
    entities:
      - light.sink_1
      - light.sink_2
      - light.table_1
      - light.table_2
      - light.table_3
      - light.garage_1
      - light.garage_2
      - light.theater_1
      - light.theater_2
      - light.theater_3
      - light.entry_1
      - light.entry_2
      - light.entry_3
      - light.morgan_fun_1
      - light.morgan_fun_2
      - light.morgan_fun_3
      - light.morgan_fun_4
      - light.morgan_fun_5
      - light.basement_can_1
      - light.basement_can_2
      - light.basement_can_3
      - light.basement_can_4
      - light.basement_can_5
      - light.morgan_s_fun_lamp_group
      - light.morgan_s_fun_lamp_zha_zha_group_0x0001
      - light.morgankiosk
      - light.alex_laptop
      - light.alex_phone
      - light.julie_phone
      - switch.fire_tablet
      - switch.morgan_room_control
      - switch.garage_opener_restart
      - input_boolean.alarm_clock
      - input_boolean.alex_basement
      - input_boolean.show_commute
      - input_boolean.tv
      - input_boolean.projector
      - light.bar_blue_led
      - light.bar_green_led
      - light.bar_red_led
      - light.bottom_of_stairs_blue_led
      - light.bottom_of_stairs_green_led
      - light.bottom_of_stairs_red_led
      - light.entry_blue_led
      - light.entry_green_led
      - light.entry_red_led
      - light.top_of_stairs_blue_led
      - light.top_of_stairs_green_led
      - light.top_of_stairs_red_led
      - light.blue_room_switch_red_led
      - light.blue_room_switch_white_led
      - light.back_door_switch_red_led
      - light.back_door_switch_white_led
      - light.theater_switch_red_led
      - light.theater_switch_white_led
    event_types:
      - service_removed
      - service_executed
      - platform_discovered
      - feedreader
      - service_registered
      - call_service
      - component_loaded
      - logbook_entry
      - system_log_event

# Enables support for tracking state changes over time
history:


# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

zwave:
  usb_path: /dev/ttyUSB0

zha:
  #usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

folder_watcher:
  - folder: /config
    patterns:
      - '*.yaml'

config_check:

# Switches


# Sensors
sensor:
  # Weather prediction
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: load_15m
      - type: processor_use
  - platform: darksky
    api_key: !secret darksky_api
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - summary
      - icon
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - cloud_cover
    scan_interval:
      minutes: 5
  - platform: waze_travel_time
    name: "To Home"
    origin: !secret work
    destination: !secret home
    region: 'US'
  - platform: waze_travel_time
    name: "To Work"
    origin: !secret home
    destination: !secret work
    region: 'US'
  # - platform: rest
  #   name: My Config
  #   resource: !secret config_url
  #   authentication: basic
  #   value_template: "{{ value_json.version }}"
  #   json_attributes:
  #     - components
  #     - unit_system
  #     - config_dir
  #   headers:
  #     Content-Type: application/json
  #     Authorization: !secret auth_token
  #     User-Agent: Home Assistant REST sensor
  - platform: time_date
    display_options:
      - 'time'
  - platform: template
    sensors:
      local_time:
        value_template: "{{ as_local(states.sensor.time.last_changed).strftime('%-I:%M %p') }}"
      rounded_temp:
        value_template: "{{ states('sensor.dark_sky_temperature')|round|int }}"
        unit_of_measurement: "°"
      pi_temp:
        value_template: "{{ '%0.0f'| format((states('sensor.rpi3_temperature')|float -32) * (5/9)) }}"
        unit_of_measurement: "°"
      harmony_activity:
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
        friendly_name: 'Harmony Activity'
      harmony_activity_upstairs:
        value_template: '{{ states.remote.harmony_hub_upstairs.attributes.current_activity }}'
        friendly_name: 'Harmony Activity Upstairs'
      kitchen_motion_battery:
        value_template: "{{ states.zwave.zooz_zse40_4_in_1_sensor.attributes.battery_level }}"
        friendly_name: "Kitchen Motion Battery"
        unit_of_measurement: '%'
  - platform: min_max
    type: mean
    round_digits: 1
    name: Downstairs Temperature
    entity_ids:
      - sensor.bar_button
      - sensor.theater_button
  - platform: min_max
    type: mean
    name: Upstairs Temperature
    round_digits: 1
    entity_ids:
      - sensor.stairs_button
  - platform: dnsip
  - platform: mqtt
    name: CPU Temperature
    state_topic: "pve/cpu_temp"
    value_template: "{{ value | multiply(0.001) | round(1) }}"
  - platform: mqtt
    name: Proxmox Updates Available
    state_topic: "pve/upgrades"
  - platform: mqtt
    name: Ubuntu LXC Updates Available
    state_topic: "ubuntu/upgrades"
  - platform: mqtt
    name: 11ty-dev LXC Updates Available
    state_topic: "11ty-dev/upgrades"
  - platform: mqtt
    name: Temperature Probe 1
    state_topic: "temperature/outside/grill/probe1"
    unit_of_measurement: "°"
  - platform: mqtt
    name: Temperature Probe 2
    state_topic: "temperature/outside/grill/probe2"
    unit_of_measurement: "°"
  - platform: mqtt
    name: Temperature Probe 3
    state_topic: "temperature/outside/grill/probe3"
    unit_of_measurement: "°"
  - platform: mqtt
    name: Temperature Probe 4
    state_topic: "temperature/outside/grill/probe4"
    unit_of_measurement: "°"
  - platform: mqtt
    name: Propane Level
    state_topic: "temperature/outside/grill/propane_level"
    unit_of_measurement: "%"
  - platform: mqtt
    name: iGrill Battery Level
    state_topic: "temperature/outside/grill/battery_level"
    unit_of_measurement: "%"

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
  
device_tracker:
  - platform: mqtt
    devices:
      alex: 'location/alex'
      julie: 'location/julie'

proximity:
  alex:
    zone: home
    devices:
      - device_tracker.alex_mobile_app
    unit_of_measurement: mi
  julie:
    zone: home
    devices:
      - device_tracker.julie_mobile_app
    unit_of_measurement: mi

# Cloud
cloud:

http:
  cors_allowed_origins:
    - "http://192.168.0.202:8080/"

light:
  - platform: group
    name: Kitchen Table
    entities:
      - light.table_1
      - light.table_2
      - light.table_3
  - platform: group
    name: Kitchen Sink
    entities:
      - light.sink_1
      - light.sink_2
  - platform: group
    name: Garage
    entities:
      - light.garage_1
      - light.garage_2
  - platform: group
    name: Theater
    entities:
      - light.theater_1
      - light.theater_2
      - light.theater_3
      - light.basement_can_1
      - light.basement_can_2
  - platform: group
    name: Entry
    entities:
      - light.entry_1
      - light.entry_2
      - light.entry_3
  - platform: group
    name: Morgan's Fun Lamp Group
    entities:
      - light.morgan_fun_1
      - light.morgan_fun_2
      - light.morgan_fun_3
      - light.morgan_fun_4
      - light.morgan_fun_5
  - platform: group
    name: Main Room
    entities:
      - light.kitchen_table
      - light.chandelier
      - light.dining_lamp   
  - platform: group
    name: Rec Room
    entities:
      - light.basement_can_3
      - light.basement_can_4
      - light.basement_can_5
  - platform: template
    lights:
      morgan_fun:
        friendly_name: "Morgan's Fun Lamp"
        level_template: >-
          {% if states.light.morgan_fun_1.attributes.brightness %}
            {{states.light.morgan_fun_1.attributes.brightness | int}}
          {% else %}
            0
          {% endif %}
        value_template: >-
          {% if states.light.morgan_fun_1.attributes.brightness %}
            on
          {% else %}
            off
          {% endif %}
        turn_on:
          event: morgan_fun
          event_data:
           status: "on"
        turn_off:
          event: morgan_fun
          event_data:
           status: "off"
        set_level:
          event: morgan_fun_level
          event_data_template:
           brightness: "{{ brightness }}"

media_player:
  - platform: onkyo
    host: !secret onkyo
    name: receiver
    receiver_max_volume: 91
  # - platform: xboxone
  #   device: !secret xboxone
  #   name: Xbox One
      
telegram_bot: !secret telegram_bot
    
notify: !secret notify
    
    
#android_ip_webcam:
#  - host: 192.168.0.118
#    port: 8080
#    sensors:
#      - motion

remote:
  - platform: harmony
    name: Harmony Hub
    host: !secret harmony
  - platform: harmony
    name: Harmony Hub Upstairs
    host: !secret harmony_upstairs
      
rest_command:
  google_backup:
    url: 'http://localhost:8055/gb/doBackup'
    timeout: '300'
    
input_boolean:
  vacation_mode:
    name: Vacation Mode
  night_mode:
    name: Night Mode
  circadian_lighting:
    name: Circadian Lighting
  guest_mode:
    name: Guest Mode
  white_noise:
    name: White Noise
  white_noise_morgan:
    name: Morgan's White Noise
  show_commute:
    name: Show Commute
  alex_bed:
    name: Alex Bed
  alex_basement:
    name: Alex Basement
  julie_bed:
    name: Julie Bed
  alarm_clock:
    name: Alarm Clock Triggered
  tv:
    name: TV
  projector:
    name: Projector
    
input_select:
  front_light_mode:
    name: Front Light Mode
    options:
      - Standard
      - Christmas
      - Halloween
      - Independence Day
      - Chiefs
  morgan_lamp_mode:
    name: Morgan's Lamp Mode
    options:
      - Standard
      - Focus
      - Princess
      - Rainbow
      - Jungle
      - Ocean
      - Halloween
      - Christmas
      - Red
  basement_scene:
    name: Basement Scene
    options:
      - None
      - Blue/Gold
      - Light Blue
      - Red/Gold
      - Red
      - Gold
      - Green
      - Green/Gold
      - Purple/Pink
      - Rainbow
  tree_mode:
    name: Christmas Tree Mode
    options:
      - "Off"
      - Breathe
      - Color
      - White
      - Dim Color
      - Dim White

input_number:
  tablet_level:
    min: 0
    max: 100
  tablet_battery:
    min: 0
    max: 100
  tablet_battery_morgan:
    min: 0
    max: 100

input_datetime:

browser_mod:
  devices:
    e4e2b7ae-bf3c6a52:
      name: morgankiosk
  disable:
    - all

stream:

breaking_changes:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
