resources:
  #HACS Resources (Updated Automatically)
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/text-element/text-element.js
    type: js
  - url: /community_plugin/lovelace-gap-card/gap-card.js
    type: js
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: js
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  - url: /community_plugin/lovelace-card-modder/card-modder.js
    type: js
  - url: /community_plugin/lovelace-card-loader/card-loader.js
    type: js
  - url: /community_plugin/lovelace-popup-card/popup-card.js
    type: js
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  #Non-HACS Resources
  - url: /local/custom-lovelace/weather-card/dark-sky-weather-card.js?v=7.3
    type: module
  - url: 'https://fonts.googleapis.com/css?family=Lato'
    type: css
  - url: /local/custom-lovelace/font.css?v=3
    type: css
  - url: /local/custom-lovelace/card-templater/lovelace-card-templater.js?v=0.0.2
    type: js
  #popup fix
  - url: /local/custom-lovelace/popupfix.js?v=7
    type: js
title: Home
popup_cards:
  light.morgan_fun:
    title: Morgan's Fun Lamp
    card:
      type: 'custom:card-modder'
      style:
        box-shadow: none
        '--paper-card-background-color': 'rgba(255,255,255,0)'
      extra_styles: >
        .card-content {
          padding: 0px;
        }
      card:
        type: entities
        entities:
          - type: 'custom:slider-entity-row'
            entity: light.morgan_fun
            toggle: true
            full_row: true
            name: Switch
          - entity: input_select.morgan_lamp_mode
            name: Mode
cch:
  background: 'rgba(51,51,51,0.6)'
  clock: voice
  clock_format: '12'
  exceptions:
    - conditions:
        user: morgankiosk
      config:
        kiosk_mode: true
        swipe: false
        show_tabs: '7'
    - conditions:
        user_agent: Android
      config:
        menu: hide
        options: hide
        hide_tabs: '7'
    - conditions:
        user: Julie
        user_agent: Android
      config:
        menu: hide
        options: hide
        hide_tabs: '6,7'
        disable_sidebar: true
  notifications: overflow
  voice: hide
  swipe: true
  swipe_animate: swipe
views:
  - !include /config/lovelace/lights-mobile.yaml
  - !include /config/lovelace/weather-mobile.yaml
  - !include /config/lovelace/security-mobile.yaml
  - !include /config/lovelace/remote_upstairs.yaml
  - !include /config/lovelace/remote_downstairs.yaml
  - !include /config/lovelace/tv-mobile.yaml
  - !include /config/lovelace/system-mobile.yaml
  - !include /config/lovelace/morgan.yaml