resources:
  #HACS Resources (Updated Automatically)
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/text-element/text-element.js
    type: js
  - url: /community_plugin/lovelace-gap-card/gap-card.js
    type: js
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: js
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  - url: /community_plugin/lovelace-card-modder/card-modder.js
    type: js
  - url: /community_plugin/lovelace-card-loader/card-loader.js
    type: js
  - url: /community_plugin/lovelace-popup-card/popup-card.js
    type: js
  #Non-HACS Resources
  - url: /local/custom-lovelace/weather-card/dark-sky-weather-card.js?v=7.3
    type: module
  - url: 'https://fonts.googleapis.com/css?family=Lato'
    type: css
  - url: /local/custom-lovelace/font.css
    type: css
  - url: /local/custom-lovelace/card-templater/lovelace-card-templater.js?v=0.0.2
    type: js
  #card-tools not currently supported by HACS
  - url: /local/custom-lovelace/card-tools/card-tools.js?v=4
    type: js
title: Home
popup_cards:
  light.morgan_fun:
    title: Morgan's Fun Lamp
    card:
      type: 'custom:card-modder'
      style:
        box-shadow: none
        '--paper-card-background-color': 'rgba(255,255,255,0)'
      card:
        type: entities
        entities:
          - type: 'custom:slider-entity-row'
            entity: light.morgan_fun
            toggle: true
            full_row: true
            name: Switch
          - entity: input_select.morgan_lamp_mode
            name: Mode
views:
  - !include /config/lovelace/lights-mobile.yaml
  - !include /config/lovelace/weather-mobile.yaml
  - !include /config/lovelace/security-mobile.yaml
  - !include /config/lovelace/tv-mobile.yaml
  - !include /config/lovelace/remote.yaml
  - !include /config/lovelace/system-mobile.yaml
  - !include /config/lovelace/morgan.yaml