esphome:
  name: bar_light
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "bar_light_hs"
    password: !secret bar_light_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

output:
  - platform: esp8266_pwm
    id: red
    pin:
      number: GPIO0
      inverted: True

  - platform: esp8266_pwm
    id: green
    pin:
      number: GPIO12
      inverted: True

  - platform: esp8266_pwm
    id: blue
    pin:
      number: GPIO2
      inverted: True

light:
  - platform: monochromatic
    name: "Bar Red LED"
    output: red
    id: red_light
  
  - platform: monochromatic
    name: "Bar Green LED"
    output: green
    id: green_light

  - platform: monochromatic
    name: "Bar Blue LED"
    output: blue
    id: blue_light

binary_sensor:
  - platform: gpio
    # https://esphome.io/components/binary_sensor/gpio.html
    pin:
      number: GPIO13
      inverted: true
    id: button
    name: Bar Lights Button
    on_multi_click:
    - timing:
        - ON for at least 0.75s
      then:
        - logger.log: "Held"
        - while:
            condition:
              binary_sensor.is_on: button
            then:
              - homeassistant.service:
                  service: light.turn_on
                  data:
                    entity_id: light.bar_bulb
                    brightness_step_pct: '-10'
              - delay: 0.5s
    - timing:
        - ON for at most 0.75s
        - OFF for at most 0.5s
        - ON for at least 0.75s
      then:
        - logger.log: "Double Clicked and Held"
        - while:
            condition:
              binary_sensor.is_on: button
            then:
              - homeassistant.service:
                  service: light.turn_on
                  data:
                    entity_id: light.bar_bulb
                    brightness_step_pct: '10'
              - delay: 0.5s
    - timing:
        - ON for at most 0.75s
        - OFF for at least 0.5s
      then:
        - logger.log: "Single Clicked"
        - if:
            condition:
              text_sensor.state:
                id: light_state
                state: 'off'
            then:
              - homeassistant.service:
                  service: light.turn_on
                  data:
                    entity_id: light.bar_bulb
                    brightness_pct: '60'
            else:
              - homeassistant.service:
                  service: light.turn_off
                  data:
                    entity_id: light.bar_bulb
    - timing:
        - ON for at most 0.75s
        - OFF for at most 0.5s
        - ON for at most 0.75s
        - OFF for at most 0.5s
        - ON for at most 0.75s
        - OFF for at most 0.5s
        - ON for at most 0.75s
        - OFF for at most 0.5s
        - ON for at most 0.75s
      then:
        - logger.log: "Five Clicks"
        - switch.toggle: relay
    # - timing: (future)
    #     - ON for at most 0.75s
    #     - OFF for at most 0.5s
    #     - ON for at most 0.75s
    #   then:
    #     - logger.log: "Double Clicked"
    #     - if:
    #         condition:
    #           text_sensor.state:
    #             id: group_state
    #             state: 'off'
    #         then:
    #           - homeassistant.service:
    #               service: homeassistant.turn_on
    #               data:
    #                 entity_id: group.dining
    #         else:
    #           - homeassistant.service:
    #               service: homeassistant.turn_off
    #               data:
    #                 entity_id: group.dining
    internal: True
    
switch:
  - platform: gpio
    # https://esphome.io/components/switch/gpio
    pin: GPIO15
    id: relay
    restore_mode: ALWAYS_ON
    on_turn_off:
      - light.turn_on: red_light
      - light.turn_off: blue_light
    on_turn_on:
      - light.turn_off: red_light

text_sensor:
  - platform: homeassistant
    id: light_state
    name: "Bar Light State"
    entity_id: light.bar_bulb
    internal: True
    on_value:
      then:
        lambda: |-
          if(x == "on") {
            auto call = id(blue_light).turn_off();
            call.perform();
          }
          else {
            auto call = id(blue_light).turn_on();
            call.perform();
          }
  # - platform: homeassistant
  #   id: group_state
  #   name: "Dining Group State"
  #   entity_id: group.dining
  #   internal: True