esphome:
  name: living_main_lights
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "living_main_hs"
    password: !secret living_main_pass

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  level: NONE

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: uptime
    name: Living Room Main Lights Uptime
    
  - platform: wifi_signal
    name: Living Room Main Lights Wifi Signal
    update_interval: 60s

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  
tuya:

light:
  - platform: "tuya"
    name: "Living Room Main Lights"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 10
    max_value: 1000