##This is for the old fan lights. Will need to be reflashed

esphome:
  name: living_fan_lights
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "living_fan_hs"
    password: !secret living_fan_pass

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  level: NONE

# Enable Home Assistant API
api:

ota:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  
tuya:

light:
  - platform: "tuya"
    name: "Living Room Fan Light"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 10
    max_value: 1444